version: 1.2

vars:
  GLOBAL: "false"  # Set to true if you want to copy the binary to /usr/local/bin

setup:
  - name: "Install dependencies"
    command: "go mod tidy"
  - name: "Generate documentation"
    command: "go run main.go generate-docs"

parallel:
  - name: "Code quality checks"
    commands:
      - "go vet ./..."
      - "golangci-lint run ./..."

steps:
  - name: "Build binary"
    command: "go build -o gitgeist main.go"

post_build:
  - name: "Moving binary"
    command: "mv gitgeist output/gitgeist"
  - name: "Copying binary to global path"
    command: "cp output/gitgeist /usr/local/bin"
    if: "$GLOBAL == true"

ignore:
  - "output/*"
  - "cfg/*"
  - ".git/*"
  - "*.log"
  - "build.yaml"
  - "readme.md"