version: 1.1

vars:
  GLOBAL: "false"

setup:
  - name: "Install dependencies"
    command: "go mod tidy"

parallel:
  - name: "Code quality checks"
    commands:
      - "go vet ./..."
      - "golangci-lint run ./..."

steps:
  - name: "Build binary"
    command: "go build -o gitgeist ./cmd"

post_build:
  - name: "Moving binary"
    command: "mv gitgeist output/gitgeist"
  - name: "Copying binary to global path"
    command: "cp output/gitgeist /usr/local/bin"
    if: "$GLOBAL == true"

ignore:
  - "output/*"
  - "cfg/*"
  - ".git/*"
  - "*.log"
  - "build.yaml"
  - "readme.md"