commit_message_patterns:
  - '(?i)^fix$'
  - '(?i)^wip'
  - '(?i)final'
  - '(?i)temp'
  - '(?i)debug'

commit_message_length:
  min: 5
  max: 100

file_inspection_patterns:
  - 'console\.log'
  - 'debugger'
  - 'dd'
  - 'dump'
  - 'TODO'